export const GETUSERS = 'users/GETUSERS'
export const GETUSER = 'users/GETUSER'
export const STOREUSER = 'users/STOREUSER'
export const DELETEUSER = 'users/DELETEUSER'
export const UPDATEUSER = 'users/DELETEUSER'
